
export const TOUR_DATES = [
  { date: "MAY 25", venue: "The Local Pub", location: "Nashville, TN", link: "#" },
  { date: "JUN 01", venue: "Summer Jam Festival", location: "Franklin, TN", link: "#" },
  { date: "JUN 12", venue: "Private Event", location: "Louisville, KY", link: "#" },
  { date: "JUN 20", venue: "The Rooftop Bar", location: "Atlanta, GA", link: "#" },
  { date: "JUL 04", venue: "City Fireworks Stage", location: "Nashville, TN", link: "#" },
];

export const SONG_LIST = [
  { title: "5-1-5-0", artist: "Dierks Bentley", genres: ["Country", "Modern Country"] },
  { title: "Ain’t No Sunshine", artist: "Bill Withers", genres: ["Soul", "R&B", "70s"] },
  { title: "Alive", artist: "Pearl Jam", genres: ["90s", "Grunge", "Rock"] },
  { title: "All Right Now", artist: "Free", genres: ["Classic Rock", "70s"] },
  { title: "Already Gone", artist: "Eagles", genres: ["Classic Rock", "70s", "Country Rock"] },
  { title: "Amber", artist: "311", genres: ["90s", "Alt Rock", "Reggae Rock"] },
  { title: "Amen", artist: "Shaboozey, Jelly Roll", genres: ["Country", "Modern Country", "Hip Hop"] },
  { title: "American Girl", artist: "Tom Petty", genres: ["Classic Rock", "70s"] },
  { title: "American Woman", artist: "Lenny Kravitz", genres: ["Classic Rock", "90s", "Rock"] },
  { title: "Amie", artist: "Pure Prairie League", genres: ["70s", "Country Rock", "Classic Rock"] },
  { title: "Are You Gonna Be My Girl", artist: "Jet", genres: ["2000s", "Rock"] },
  { title: "Baby, I Love Your Way", artist: "Peter Frampton", genres: ["Classic Rock", "70s"] },
  { title: "Baker Street", artist: "Gerry Rafferty", genres: ["Classic Rock", "70s"] },
  { title: "Beat It", artist: "Michael Jackson", genres: ["80s", "Pop", "Rock"] },
  { title: "Beautiful Day", artist: "U2", genres: ["2000s", "Rock", "Pop"] },
  { title: "Beer In Mexico", artist: "Kenny Chesney", genres: ["Country", "Modern Country"] },
  { title: "Best Day Of My Life", artist: "American Authors", genres: ["2010s", "Pop", "Indie Pop"] },
  { title: "Best Thing Since Backroads", artist: "Jake Owen", genres: ["Country", "Modern Country"] },
  { title: "Bigger Than My Body", artist: "John Mayer", genres: ["2000s", "Pop Rock"] },
  { title: "Billie Jean", artist: "Michael Jackson", genres: ["80s", "Pop", "Dance"] },
  { title: "Bitter Sweet Symphony", artist: "The Verve", genres: ["90s", "Alt Rock"] },
  { title: "Blue On Black", artist: "Kenny Wayne Shepherd", genres: ["90s", "Blues Rock", "Rock"] },
  { title: "Breakdown", artist: "Tom Petty", genres: ["Classic Rock", "70s"] },
  { title: "Breathe", artist: "Pink Floyd", genres: ["Classic Rock", "70s", "Psychedelic Rock"] },
  { title: "Broken Wings", artist: "Mr. Mister", genres: ["80s", "Pop Rock"] },
  { title: "Brown Eyed Girl", artist: "Van Morrison", genres: ["Classic Rock", "60s", "Pop"] },
  { title: "Budapest", artist: "George Ezra", genres: ["2010s", "Pop", "Folk Pop"] },
  { title: "Can’t Find My Way Home", artist: "Blind Faith", genres: ["Classic Rock", "60s"] },
  { title: "Can’t Help Falling In Love", artist: "Elvis Presley", genres: ["60s", "Ballad", "Pop"] },
  { title: "Can’t Stop the Feeling", artist: "Justin Timberlake", genres: ["2010s", "Pop", "Dance"] },
  { title: "Can’t You See", artist: "The Marshall Tucker Band", genres: ["Southern Rock", "70s", "Classic Rock"] },
  { title: "Celebration", artist: "Kool & The Gang", genres: ["Funk", "Dance", "80s"] },
  { title: "Champagne Supernova", artist: "Oasis", genres: ["90s", "Britpop", "Rock"] },
  { title: "Chicken Fried", artist: "Zac Brown Band", genres: ["Country", "Modern Country"] },
  { title: "Closing Time", artist: "Semisonic", genres: ["90s", "Alt Rock"] },
  { title: "Comfortably Numb", artist: "Pink Floyd", genres: ["Classic Rock", "70s", "Progressive Rock"] },
  { title: "Counting Stars", artist: "One Republic", genres: ["2010s", "Pop Rock"] },
  { title: "Country Girl", artist: "Luke Bryan", genres: ["Country", "Modern Country"] },
  { title: "Crazy Little Thing Called Love", artist: "Queen", genres: ["Classic Rock", "80s", "Rock"] },
  { title: "Cuts Like A Knife", artist: "Bryan Adams", genres: ["Classic Rock", "80s"] },
  { title: "Desire", artist: "U2", genres: ["80s", "Rock"] },
  { title: "Don’t Stop Believin’", artist: "Journey", genres: ["80s", "Classic Rock", "Anthem"] },
  { title: "Down On the Corner", artist: "Creedence Clearwater Revival", genres: ["Classic Rock", "60s", "Rock"] },
  { title: "Drift Away", artist: "Dobie Gray", genres: ["70s", "Soul", "Classic Rock"] },
  { title: "Drive", artist: "Incubus", genres: ["90s", "Alt Rock", "2000s"] },
  { title: "D’You Know What I Mean?", artist: "Oasis", genres: ["90s", "Britpop"] },
  { title: "Easy", artist: "Lionel Richie", genres: ["70s", "Soul", "Pop"] },
  { title: "Everlong", artist: "Foo Fighters", genres: ["90s", "Alt Rock", "Rock"] },
  { title: "Everybody Talks", artist: "Neon Trees", genres: ["2010s", "Pop Rock"] },
  { title: "Everything You Want", artist: "Vertical Horizon", genres: ["90s", "Alt Rock"] },
  { title: "Fast Car", artist: "Tracy Chapman", genres: ["80s", "Folk", "Singer-Songwriter"] },
  { title: "Fly", artist: "Sugar Ray", genres: ["90s", "Pop Rock"] },
  { title: "Fly Like an Eagle", artist: "Steve Miller Band", genres: ["Classic Rock", "70s"] },
  { title: "Fly Me To the Moon", artist: "Frank Sinatra", genres: ["Swing", "Jazz", "Classics"] },
  { title: "For What It’s Worth", artist: "Buffalo Springfield", genres: ["60s", "Folk Rock", "Classic Rock"] },
  { title: "Free Fallin’", artist: "Tom Petty", genres: ["Classic Rock", "80s"] },
  { title: "Get Lucky", artist: "Daft Punk", genres: ["2010s", "Dance", "Funk"] },
  { title: "Give A Little Bit", artist: "Supertramp", genres: ["Classic Rock", "70s"] },
  { title: "Go Let It Out", artist: "Oasis", genres: ["2000s", "Britpop"] },
  { title: "Gravity", artist: "John Mayer", genres: ["2000s", "Blues Pop", "Soul"] },
  { title: "Happy", artist: "Pharrell Williams", genres: ["2010s", "Pop", "Soul"] },
  { title: "Hard To Handle", artist: "The Black Crows", genres: ["Classic Rock", "90s", "Southern Rock"] },
  { title: "Have You Ever Seen the Rain", artist: "Creedence Clearwater Revival", genres: ["Classic Rock", "70s"] },
  { title: "Heartbreak Warfare", artist: "John Mayer", genres: ["2000s", "Pop Rock"] },
  { title: "How Sweet It Is", artist: "James Taylor", genres: ["70s", "Folk Pop", "Singer-Songwriter"] },
  { title: "I Can See Clearly Now", artist: "Johnny Nash", genres: ["70s", "Reggae Pop"] },
  { title: "I Can’t Drink You Away", artist: "Justin Timberlake", genres: ["2010s", "Pop", "Soul"] },
  { title: "I Got You / I Feel Good", artist: "James Brown", genres: ["Funk", "Soul", "60s"] },
  { title: "I Saw Her Standing There", artist: "The Beatles", genres: ["60s", "Rock & Roll", "Classic Rock"] },
  { title: "I Shot the Sheriff", artist: "Bob Marley", genres: ["Reggae", "70s"] },
  { title: "I Still Haven’t Found What I’m Looking For", artist: "U2", genres: ["80s", "Rock", "Classic Rock"] },
  { title: "I Won’t Back Down", artist: "Tom Petty", genres: ["Classic Rock", "80s"] },
  { title: "If You Could Only See", artist: "Tonic", genres: ["90s", "Alt Rock"] },
  { title: "Interstate Love Song", artist: "Stone Temple Pilots", genres: ["90s", "Alt Rock", "Grunge"] },
  { title: "Jenny / 867-5309", artist: "Tommy Tutone", genres: ["80s", "Pop Rock"] },
  { title: "Jet Airliner", artist: "Steve Miller Band", genres: ["Classic Rock", "70s"] },
  { title: "Knee Deep", artist: "Zac Brown Band", genres: ["Country", "Modern Country"] },
  { title: "Knockin’ On Heaven’s Door", artist: "Bob Dylan", genres: ["70s", "Folk Rock", "Classic Rock"] },
  { title: "Last Train Home", artist: "John Mayer", genres: ["2020s", "Pop Rock", "80s Inspired"] },
  { title: "Lay Down Sally", artist: "Eric Clapton", genres: ["Classic Rock", "70s", "Country Rock"] },
  { title: "Layla", artist: "Eric Clapton", genres: ["Classic Rock", "70s", "Blues Rock"] },
  { title: "Learn To Fly", artist: "Foo Fighters", genres: ["90s", "Alt Rock"] },
  { title: "Learning To Fly", artist: "Tom Petty", genres: ["Classic Rock", "90s"] },
  { title: "Let’s Stay Together", artist: "Al Green", genres: ["70s", "Soul", "R&B"] },
  { title: "Life Is A Highway", artist: "Rascal Flatts", genres: ["Country", "Modern Country", "2000s"] },
  { title: "Listen To the Music", artist: "The Doobie Brothers", genres: ["Classic Rock", "70s"] },
  { title: "Livin’ On A Prayer", artist: "Bon Jovi", genres: ["80s", "Classic Rock", "Anthem"] },
  { title: "Long Train Runnin’", artist: "The Doobie Brothers", genres: ["Classic Rock", "70s"] },
  { title: "Love Song", artist: "311", genres: ["90s", "Alt Rock", "Reggae Rock"] },
  { title: "Lovely Day", artist: "Bill Withers", genres: ["70s", "Soul", "Funk"] },
  { title: "Margaritaville", artist: "Jimmy Buffet", genres: ["Classic Rock", "70s", "Trop Rock"] },
  { title: "Mexico", artist: "James Taylor", genres: ["70s", "Folk Pop"] },
  { title: "My Girl", artist: "The Temptations", genres: ["60s", "Soul", "R&B"] },
  { title: "Never There", artist: "Cake", genres: ["90s", "Alt Rock"] },
  { title: "New Sensation", artist: "INXS", genres: ["80s", "Rock", "Pop"] },
  { title: "Nobody to Blame", artist: "Chris Stapleton", genres: ["Country", "Modern Country"] },
  { title: "Oh, Pretty Woman", artist: "Roy Orbison", genres: ["60s", "Classic Rock"] },
  { title: "One Headlight", artist: "The Wallflowers", genres: ["90s", "Alt Rock"] },
  { title: "Plush", artist: "Stone Temple Pilots", genres: ["90s", "Alt Rock", "Grunge"] },
  { title: "Pontoon", artist: "Little Big Town", genres: ["Country", "Modern Country"] },
  { title: "Pride / In the Name Of Love", artist: "U2", genres: ["80s", "Rock"] },
  { title: "Proud Mary", artist: "Tina Turner", genres: ["Soul", "Classic Rock", "70s"] },
  { title: "Queen of California", artist: "John Mayer", genres: ["2010s", "Folk Rock", "Americana"] },
  { title: "Red Solo Cup", artist: "Toby Keith", genres: ["Country", "Modern Country"] },
  { title: "Rock’n Me Baby", artist: "Steve Miller Band", genres: ["Classic Rock", "70s"] },
  { title: "Refugee", artist: "Tom Petty", genres: ["Classic Rock", "70s"] },
  { title: "Rocket Man", artist: "Elton John", genres: ["70s", "Pop Rock", "Classic Rock"] },
  { title: "Roxanne", artist: "The Police", genres: ["Classic Rock", "70s", "Alt Rock"] },
  { title: "Rude", artist: "MAGIC!", genres: ["2010s", "Reggae Pop"] },
  { title: "Runnin’ Down A Dream", artist: "Tom Petty", genres: ["Classic Rock", "80s"] },
  { title: "Save A Horse Ride A Cowboy", artist: "Big & Rich", genres: ["Country", "Modern Country"] },
  { title: "September", artist: "Earth, Wind & Fire", genres: ["Funk", "Soul", "70s"] },
  { title: "Seven Bridges Road", artist: "Eagles", genres: ["70s", "Country Rock", "Classic Rock"] },
  { title: "She’s Country", artist: "Jason Aldean", genres: ["Country", "Modern Country"] },
  { title: "Shut Up and Dance", artist: "Walk the Moon", genres: ["2010s", "Pop Rock"] },
  { title: "Sideways", artist: "Dierks Bentley", genres: ["Country", "Modern Country"] },
  { title: "Sit Next to Me", artist: "Foster The People", genres: ["2010s", "Alt Pop"] },
  { title: "Sittin’ On the Dock of the Bay", artist: "Otis Redding", genres: ["60s", "Soul"] },
  { title: "Sleep Walk", artist: "Santo & Johnny", genres: ["50s", "Instrumental"] },
  { title: "Something", artist: "The Beatles", genres: ["Classic Rock", "60s"] },
  { title: "Spoonman", artist: "Soundgarden", genres: ["90s", "Grunge"] },
  { title: "Stand By Me", artist: "Ben E. King", genres: ["60s", "Soul"] },
  { title: "Stuck In the Middle With You", artist: "Stealers Wheel", genres: ["Classic Rock", "70s"] },
  { title: "Sugar", artist: "Maroon 5", genres: ["2010s", "Pop"] },
  { title: "Summertime", artist: "Kenny Chesney", genres: ["Country", "Modern Country"] },
  { title: "Summer Breeze", artist: "Seals & Crofts", genres: ["70s", "Soft Rock"] },
  { title: "Summer of 69", artist: "Bryan Adams", genres: ["80s", "Classic Rock"] },
  { title: "Supermassive Black Hole", artist: "Muse", genres: ["2000s", "Alt Rock"] },
  { title: "Superstition", artist: "Stevie Wonder", genres: ["Funk", "Soul", "70s"] },
  { title: "Sweet Caroline", artist: "Neil Diamond", genres: ["60s", "Classic Pop", "Anthem"] },
  { title: "Sweet Child O’ Mine", artist: "Guns N’ Roses", genres: ["80s", "Hard Rock"] },
  { title: "Sweet Emotion", artist: "Aerosmith", genres: ["Classic Rock", "70s"] },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", genres: ["Southern Rock", "70s", "Classic Rock"] },
  { title: "Take It Easy", artist: "Eagles", genres: ["Classic Rock", "70s", "Country Rock"] },
  { title: "Take Me Home, Country Roads", artist: "John Denver", genres: ["70s", "Country", "Folk"] },
  { title: "Tennessee Whiskey", artist: "Chris Stapleton", genres: ["Country", "Modern Country", "Soul"] },
  { title: "The Middle", artist: "Jimmy Eat World", genres: ["2000s", "Alt Rock"] },
  { title: "The Way You Look Tonight", artist: "Frank Sinatra", genres: ["Jazz", "Swing"] },
  { title: "They Call Me the Breeze", artist: "Eric Clapton", genres: ["Classic Rock", "70s"] },
  { title: "Three Little Birds / Every Little Thing Gonna Be Alright", artist: "Bob Marley", genres: ["Reggae", "70s"] },
  { title: "Ticket to Ride", artist: "The Beatles", genres: ["60s", "Classic Rock"] },
  { title: "Toes", artist: "Zac Brown Band", genres: ["Country", "Modern Country"] },
  { title: "Treasure", artist: "Bruno Mars", genres: ["2010s", "Pop", "Funk"] },
  { title: "Two Princes", artist: "Spin Doctors", genres: ["90s", "Alt Rock"] },
  { title: "Uptown Funk", artist: "Bruno Mars", genres: ["2010s", "Funk", "Pop"] },
  { title: "Use Somebody", artist: "Kings of Leon", genres: ["2000s", "Alt Rock"] },
  { title: "Vultures", artist: "John Mayer", genres: ["2000s", "Blues Rock"] },
  { title: "Wagon Wheel", artist: "Darius Rucker", genres: ["Country", "Modern Country"] },
  { title: "Wanted Dead or Alive", artist: "Bon Jovi", genres: ["80s", "Hard Rock", "Classic Rock"] },
  { title: "What I Got", artist: "Sublime", genres: ["90s", "Alt Rock", "Reggae Rock"] },
  { title: "What Was I Thinkin’", artist: "Dierks Bentley", genres: ["Country", "Modern Country"] },
  { title: "When the Sun Goes Down", artist: "Kenny Chesney", genres: ["Country", "Modern Country"] },
  { title: "Where Are You Going", artist: "Dave Matthews Band", genres: ["2000s", "Alt Rock"] },
  { title: "Wish You Were Here", artist: "Pink Floyd", genres: ["Classic Rock", "70s"] },
  { title: "Wonderwall", artist: "Oasis", genres: ["90s", "Britpop"] },
  { title: "You Are the Best Thing", artist: "Ray LaMontagne", genres: ["2000s", "Soul"] },
  { title: "You Look Wonderful Tonight", artist: "Eric Clapton", genres: ["70s", "Classic Rock"] },
  { title: "You Wreck Me", artist: "Tom Petty", genres: ["90s", "Classic Rock"] },
];

export const VIDEOS = [
  { id: "1", title: "Live Performance", url: "https://www.youtube.com/embed/j6HxftubphU?list=PL3senXUbh3QVfktpYxbipVpPcG3xZE1CK" },
  { id: "2", title: "Promo Reel", url: "https://www.youtube.com/embed/g3Lynto34lQ?list=PL3senXUbh3QUtqA1zM8w8ckIujJSj87mN" },
];

export const TIP_LINKS = {
  payment: "https://venmo.com/u/lukequeenband",
  paypal: "https://www.paypal.com/ncp/payment/UBJKX2SSJJ7HW",
};
